[package]
name = "stoi"
version = "0.1.0"
edition = "2024"

[lib]
name = "stoi"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.27.1"
pyo3 = "0.27.2"
stoilib = { path = "../stoilib" }
rayon = "1.11.0"
